#!/bin/bash
# vim:syntax=sh

mode=0400
dirmode=0700

content='ForwardX11            no
HashKnownHosts        no
ServerAliveInterval   60
ForwardAgent          yes

StrictHostKeyChecking accept-new

ControlMaster         auto
# Openssh now steals 16 characters to try to be atomic. This is annoying even
# for nor normal-sized hostnames, but moving the controlsockets to ~/.shc gives
# us back 8 characters, so yay?
ControlPath           ~/.shc/%h_%p_%r
ControlPersist        yes

Host *.dc.perl.space
ProxyJump gateway.perl.space
'

if [ -e ~/.ssh/config-local ]; then
    content="$content

$(cat ~/.ssh/config-local)"
fi

content="$content

Host                  github.com launchpad.net
IdentityFile          ~/.ssh/id_rsa_git

Host                  koekblik.kaarsemaker.net beschuitbus.kaarsemaker.net hoektand.paroclean.nl
User                  dennis
Identityfile          ~/.ssh/id_rsa_me

Host                  *.perl.space *.perl.org
User                  dkaarsemaker"
