#!/bin/bash
# vim:syntax=sh

mode=0400
dirmode=0700

content='ForwardX11            no
HashKnownHosts        no
ServerAliveInterval   60
ForwardAgent          yes

StrictHostKeyChecking no

ControlMaster         auto
ControlPath           ~/.ssh/control/%h_%p_%r
ControlPersist        yes'

if [ -e ~/.ssh/config-local ]; then
    content="$content

$(cat ~/.ssh/config-local)"
fi

if [ -e ~/.dotfiles/ssh/config-bkng ]; then
    content="$content

$(< ~/.dotfiles/ssh/config-bkng)"
fi

if [[ -e ~/.dotfiles/ssh/config-pci && ! $HOSTNAME =~ /pc^/ ]]; then
    content="$content

$(< ~/.dotfiles/ssh/config-pci)"
fi

content="$content

Host                  10.42.* *.kaarsemaker.net kaarsemaker.net *.paroclean.nl *.seveas.net
User                  dennis
Identityfile          ~/.ssh/id_rsa_me

Host                  github.com launchpad.net
IdentityFile          ~/.ssh/id_rsa_git

Host                  *
User                  dkaarsemaker
IdentityFile          ~/.ssh/id_rsa_bkng"
