#!/bin/bash
# vim:syntax=sh

mode=0400
dirmode=0700

content='ForwardX11            no
HashKnownHosts        no
ServerAliveInterval   60
ForwardAgent          yes

StrictHostKeyChecking accept-new

ControlMaster         auto
ControlPath           ~/.ssh/control/%C
ControlPersist        yes
'

if [ -e ~/.ssh/config-local ]; then
    content="$content

$(cat ~/.ssh/config-local)"
fi

content="$content

Host                  github.com launchpad.net
IdentityFile          ~/.ssh/id_rsa_git

Host                  *.seve.as
User                  dennis
Identityfile          ~/.ssh/id_rsa_me
VerifyHostKeyDNS      true
"
